apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-inventory
  template:
    metadata:
      labels:
        app: retail-inventory
    spec:
      containers:
      - name: retail-inventory-container
        image: retail-inventory-pipeline:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000